services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      MSSQL_SA_PASSWORD: TokyoJoe138!
      ACCEPT_EULA: true
    ports:
      - 1433:1433
    volumes:
      - db-data:/var/opt/mssql
  dev:
    image: jeffrygonzalez/oncall-developer-api-dec-2022:latest
    ports: 
      - 1338:80
volumes:
  db-data: