

### Get a List Of People

GET http://localhost:1337/people HTTP/1.1
Accept: application/json


### Adding a Person

POST http://localhost:1337/people HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "firstName": "Gene",
    "lastName": "Sisko"
}


### Getting a single person
GET http://localhost:1337/people/18 HTTP/1.1
Accept: application/json

